config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  get '/home', to: 'welcome#index'
  
  
  resources :recipes
  resources :welcome
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  validates :chefname, presence: true, length: {minimum: 3, maximum: 40}
#   validates :email, presence: true, length: {maximum: 105},
#                                     uniqueness: { case_sensitive: false}, 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
                                    uniqueness: { case_sensitive: false}, 
                                      format: { with: VALID_EMAIL_REGEX }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100}
  validates :summary, presence: true, length: { minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 500}
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def new
    @recipe = Recipe.new
  end
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(2)
    
    if @recipe.save
      flash[:success] = "Your recipe has been created Successfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update 
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      #do something
      flash[:success] = "Your recipe was updated successfully!" 
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  private
      
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def new
    @chef = Chef.new
  end
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<hr/>
<footer>
  <div class="row">
    <div class="medium-4 columns"><small>&copy; Copyright material 2015</small></div>
    <div class="medium-4 columns">Feedback</div>
    <div class="medium-4 columns">Terms and Conditions</div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class= "row">
  <div class="medium-10 columns">
    <% flash.each do |message_type, message| %>
    <div data-alert class="alert-box <%= message_type %> radius">
      <%= message %>
      <a class = "close">&times;</a>
    </div>
    <% end %>
  </div>
    
</div>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'My Recipes App', root_path %></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
  
    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to 'New Recipe', new_recipe_path %></li>
        <li><a href="#">Link 2</a></li>
      </ul>
    </section>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "My Recipes App" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="well medium-8 medium-offset-2 columns">
    <%= form_for(@recipe, html: { multipart: true}) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :summary %>
    <%= f.text_field :summary %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <span class="picture">
      <%=f.file_field :picture, accept: 'image/jpeg, image/png, image/gif' %>
    </span>
    <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: 'button radius success expand') %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('chnage', function () {
    size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
        alert('Maximum file size is 5 MB. Please choose a smaller file');
     }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Recipe' %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: 'All Recipes' %>
<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="medium-2 columns">
      <div class="chef_info_center">
        <%= gravatar_for recipe.chef, size: 100 %>
        <h5>Chef Name: <%= recipe.chef.chefname %></h5>
      </div>
    </div >
    <div class="medium-6 columns well">
      <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
      <p><%= recipe.summary %></p>
      <p>
        <span class=quiet><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
      </p>

    </div>
    <div class="medium-4 columns">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'Creata a new Recipe' %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="row">
  <div class="medium-4 columns right center">
    <%= gravatar_for @recipe.chef, size: 200 %>
    <p>Brought to you by: <%= @recipe.chef.chefname %> </p>
  </div>
  <div class="medium-8 coumns">
    <%= link_to 'Edit Recipe', edit_recipe_path(@recipe), class: "button small radius" %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravata") if @recipe.picture? %>
    </div>
    <div class="well">
      <h5>Steps:</h5>
      <p><%= simple_format(@recipe.description) %></p>
    </div>
  </div>
</div>
<div class="row">
  <h5><%= link_to 'Return to Recipes', recipes_path, class: 'button small warning radius' %></h5>
</div>

app/views/shared/_errors.html.erb
<%if obj.errors.any? %>
  <div class="row">
    <div class="alert-box warning radius medium-8 medium-offset-2 columns">
      <p>Please correct the following errors</p>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<div class="row">
<p class="center">
  <h4><%= title %></h4>
  <hr/>
</p>
</div>

app/views/welcome/index.html.erb
<div class="container jumbotron">
  <div class="row centered">
    <h1>Welcome to My Recipes App</h1>
    <p>This is the Homepage for my Recipes app</p>
    
  </div>
  <div class="row">
    <%=link_to 'signup', new_welcome_path , class: "button radius centered expand success" %>
    <%=link_to 'login', '#', class: "button radius centered expand" %>
  </div>
</div>
<div class="container paddder-top-medium">
  <div class="medium-4 columns">
    <h2>View recipes as a guest</h2>
    <p>Browse all the recipes as a Guest and signup later</p>
    <%= link_to 'Guest Browsing', recipes_path , class: "button expand radius" %>
  </div>
  <div class="medium-4 columns">
      <h2>View recipes as a guest</h2>
    <p>Browse through all the recipes as a guest</p>
    <%= link_to 'Guest Login', '', class: "button expand  radius" %>
    
  </div>
  <div class="medium-4 columns">
      <h2>View recipes as a guest</h2>
    <p>Browse through all the recipes as a guest</p>
    <%= link_to 'Guest Login', '', class: "button expand  radius" %>
    
  </div>
</div>

app/views/welcome/new.html.erb
<div class="row">
  <h4>Signup for or Recipes App </h4>
</div>
<div class="row">
  <div class="medium-8 medium-offset-2 columns">
    <%= form_for @chef do |c| %>
    <%= c.label :chefname %>
    <%= c.text_field :chefname %>
    <% end %>
  </div>
</div>